const state={resources:[],query:"",university:"",year:"",interviewType:"",sourceType:""};
const elements={results:document.querySelector("#results"),count:document.querySelector("#resultCount"),empty:document.querySelector("#emptyState"),searchInput:document.querySelector("#searchInput"),heroSearch:document.querySelector("#heroSearch"),heroSearchButton:document.querySelector("#heroSearchButton"),universityFilter:document.querySelector("#universityFilter"),yearFilter:document.querySelector("#yearFilter"),typeFilter:document.querySelector("#typeFilter"),sourceFilter:document.querySelector("#sourceFilter"),resetButton:document.querySelector("#resetButton")};
function normalize(value=""){return String(value).toLowerCase().replace(/\s+/g," ").trim()}
function badgeClass(sourceType){if(sourceType==="대학 공식")return"official";if(sourceType==="교육청")return"office";if(sourceType==="면접 후기")return"review";return"practice"}
function escapeHtml(value=""){return String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function resourceCard(item){const tags=(item.tags||[]).map(tag=>`<span class="tag">${escapeHtml(tag)}</span>`).join("");const link=item.url&&item.url!=="#"?`<a href="${escapeHtml(item.url)}" target="_blank" rel="noopener">자료 열기 ↗</a>`:`<span class="disabled-link">링크 준비중</span>`;return `<article class="resource-card"><div class="resource-top"><span class="badge ${badgeClass(item.sourceType)}">${escapeHtml(item.sourceType)}</span><span class="meta">${escapeHtml(item.year)}학년도</span></div><h3>${escapeHtml(item.title)}</h3><div class="meta">${escapeHtml(item.university||"공통자료")}${item.department?` · ${escapeHtml(item.department)}`:""}${item.admissionTrack?`<br>${escapeHtml(item.admissionTrack)}`:""}</div><p class="summary">${escapeHtml(item.summary||"")}</p><div class="tags">${tags}</div>${link}</article>`}
function addOptions(select,values){const sorted=[...new Set(values.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),"ko"));sorted.forEach(value=>{const option=document.createElement("option");option.value=value;option.textContent=value;select.appendChild(option)})}
function populateFilters(){addOptions(elements.universityFilter,state.resources.map(x=>x.university));addOptions(elements.yearFilter,state.resources.map(x=>x.year).sort().reverse());addOptions(elements.typeFilter,state.resources.map(x=>x.interviewType));addOptions(elements.sourceFilter,state.resources.map(x=>x.sourceType))}
function matches(item){const haystack=normalize([item.title,item.university,item.department,item.track,item.admissionTrack,item.interviewType,item.resourceType,item.sourceType,item.sourceOrg,item.summary,...(item.tags||[])].join(" "));return(!state.query||haystack.includes(normalize(state.query)))&&(!state.university||item.university===state.university)&&(!state.year||String(item.year)===String(state.year))&&(!state.interviewType||item.interviewType===state.interviewType)&&(!state.sourceType||item.sourceType===state.sourceType)}
function render(){const filtered=state.resources.filter(matches);elements.count.textContent=filtered.length;elements.results.innerHTML=filtered.map(resourceCard).join("");elements.empty.hidden=filtered.length!==0}
function syncState(){state.query=elements.searchInput.value;state.university=elements.universityFilter.value;state.year=elements.yearFilter.value;state.interviewType=elements.typeFilter.value;state.sourceType=elements.sourceFilter.value;render()}
function runHeroSearch(){const query=elements.heroSearch.value.trim();elements.searchInput.value=query;state.query=query;document.querySelector("#search").scrollIntoView({behavior:"smooth"});render()}
async function init(){try{const response=await fetch("./data/resources.json");if(!response.ok)throw new Error("자료 파일을 불러오지 못했습니다.");state.resources=await response.json();populateFilters();render();[elements.searchInput,elements.universityFilter,elements.yearFilter,elements.typeFilter,elements.sourceFilter].forEach(el=>el.addEventListener("input",syncState));elements.heroSearchButton.addEventListener("click",runHeroSearch);elements.heroSearch.addEventListener("keydown",event=>{if(event.key==="Enter")runHeroSearch()});elements.resetButton.addEventListener("click",()=>{elements.searchInput.value="";elements.universityFilter.value="";elements.yearFilter.value="";elements.typeFilter.value="";elements.sourceFilter.value="";Object.assign(state,{query:"",university:"",year:"",interviewType:"",sourceType:""});render()});document.querySelectorAll("[data-quick]").forEach(button=>{button.addEventListener("click",()=>{const keyword=button.dataset.quick;elements.searchInput.value=keyword;state.query=keyword;document.querySelector("#search").scrollIntoView({behavior:"smooth"});render()})})}catch(error){console.error(error);elements.results.innerHTML=`<div class="empty-state"><div>자료를 불러오지 못했습니다.</div><p>GitHub Pages에서 실행 중인지 확인해주세요.</p></div>`}}
init();
